// This file is auto-generated by _add-components.mjs.

import { Box, Text } from "ink";
import React, { useState, useEffect } from "react";
import type { ReactNode } from "react";

import { useTheme } from "@/components/ui/theme-provider";
import { useInput } from "@/hooks/use-input";

export type ChatRole = "user" | "assistant" | "system" | "error";

export interface ChatMessageProps {
  /** Chat author (user, assistant, …). Named `sender` to avoid clashing with DOM `role`. */
  sender: ChatRole;
  name?: string;
  timestamp?: Date;
  streaming?: boolean;
  collapsed?: boolean;
  children?: ReactNode;
}

export const ChatMessage = function ChatMessage({
  sender,
  name,
  timestamp,
  streaming = false,
  collapsed: initialCollapsed = false,
  children,
}: ChatMessageProps) {
  const theme = useTheme();
  const [isCollapsed, setIsCollapsed] = useState(initialCollapsed);
  const [dotFrame, setDotFrame] = useState(0);

  // Typing indicator animation
  useEffect(() => {
    if (!streaming) {
      return;
    }
    const id = setInterval(() => setDotFrame((f) => (f + 1) % 4), 400);
    return () => clearInterval(id);
  }, [streaming]);

  // Toggle collapse on Enter/Space when focused
  useInput((input, key) => {
    if (initialCollapsed && (key.return || input === " ")) {
      setIsCollapsed((c) => !c);
    }
  });

  const roleColor: Record<ChatRole, string> = {
    assistant: theme.colors.success ?? "green",
    error: theme.colors.error ?? "red",
    system: theme.colors.mutedForeground,
    user: theme.colors.primary,
  };

  const roleLabel: Record<ChatRole, string> = {
    assistant: "assistant",
    error: "error",
    system: "system",
    user: "user",
  };

  const color = roleColor[sender];

  const dots = ["", "●", "●●", "●●●"][dotFrame] ?? "";

  // Get first line of children for collapsed display
  const childrenText = typeof children === "string" ? children : "";
  const firstLine = childrenText.split("\n")[0] ?? "";

  return (
    <Box flexDirection="column" marginBottom={1}>
      {/* Header row */}
      <Box gap={1}>
        <Text color={color} bold>
          {name ?? roleLabel[sender]}
        </Text>
        {timestamp && (
          <Text dimColor color={theme.colors.mutedForeground}>
            {formatTime(timestamp)}
          </Text>
        )}
        {isCollapsed && !streaming && (
          <Text dimColor color={theme.colors.mutedForeground}>
            [expand]
          </Text>
        )}
      </Box>

      {/* Content */}
      {streaming ? (
        <Box>
          {children ? (
            <>{children}</>
          ) : (
            <Text color={color} dimColor>
              {dots}
            </Text>
          )}
        </Box>
      ) : isCollapsed ? (
        <Box>
          <Text dimColor>
            {firstLine.slice(0, 60)}
            {firstLine.length > 60 || childrenText.includes("\n") ? "..." : ""}
          </Text>
        </Box>
      ) : (
        <Box>{children}</Box>
      )}
    </Box>
  );
};

const formatTime = function formatTime(date: Date): string {
  return date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
};
