// This file is auto-generated by _add-components.mjs.

import { Box, Text } from "ink";
import React, { useState } from "react";

import { useTheme } from "@/components/ui/theme-provider";
import { useFocus } from "@/hooks/use-focus";
import { useInput } from "@/hooks/use-input";

export interface CheckboxProps {
  checked?: boolean;
  onChange?: (checked: boolean) => void;
  label?: string;
  indeterminate?: boolean;
  disabled?: boolean;
  id?: string;
  /** Character shown when checked. Default: '■' */
  checkedIcon?: string;
  /** Character shown when unchecked. Default: '□' */
  uncheckedIcon?: string;
  /** Character shown when indeterminate. Default: '▪' */
  indeterminateIcon?: string;
}

export const Checkbox = function Checkbox({
  checked: controlledChecked,
  onChange,
  label,
  indeterminate = false,
  disabled = false,
  id,
  checkedIcon = "■",
  uncheckedIcon = "□",
  indeterminateIcon = "▪",
}: CheckboxProps) {
  const [internalChecked, setInternalChecked] = useState(false);
  const theme = useTheme();
  const { isFocused } = useFocus({ id });

  const checked = controlledChecked ?? internalChecked;

  useInput((input) => {
    if (!isFocused || disabled) {
      return;
    }
    if (input === " ") {
      const next = !checked;
      onChange ? onChange(next) : setInternalChecked(next);
    }
  });

  const icon = indeterminate
    ? indeterminateIcon
    : checked
      ? checkedIcon
      : uncheckedIcon;
  const iconColor = disabled
    ? theme.colors.mutedForeground
    : checked || indeterminate
      ? theme.colors.primary
      : theme.colors.border;

  return (
    <Box gap={1}>
      <Text
        color={isFocused ? theme.colors.focusRing : iconColor}
        bold={isFocused}
      >
        {icon}
      </Text>
      {label && (
        <Text
          color={
            disabled ? theme.colors.mutedForeground : theme.colors.foreground
          }
          dimColor={disabled}
        >
          {label}
        </Text>
      )}
    </Box>
  );
};
