// This file is auto-generated by _add-components.mjs.

import { Text } from "ink";
import React from "react";

import { useTheme } from "@/components/ui/theme-provider";

export interface NotificationBadgeProps {
  count: number;
  color?: string;
}

export const NotificationBadge = function NotificationBadge({
  count,
  color,
}: NotificationBadgeProps) {
  const theme = useTheme();
  if (count === 0) {
    return null;
  }
  const resolvedColor = color ?? theme.colors.error;
  return <Text color={resolvedColor}>[{count}]</Text>;
};
