// This file is auto-generated by _add-components.mjs.
import * as React from "react";

type BorderStyle =
  | "single"
  | "double"
  | "round"
  | "bold"
  | "singleDouble"
  | "doubleSingle"
  | "classic";

export interface ColorTokens {
  primary: string;
  primaryForeground: string;
  secondary: string;
  secondaryForeground: string;
  accent: string;
  accentForeground: string;
  success: string;
  successForeground: string;
  warning: string;
  warningForeground: string;
  error: string;
  errorForeground: string;
  info: string;
  infoForeground: string;
  background: string;
  foreground: string;
  muted: string;
  mutedForeground: string;
  border: string;
  focusRing: string;
  selection: string;
  selectionForeground: string;
}

export interface SpacingTokens {
  0: number;
  1: number;
  2: number;
  3: number;
  4: number;
  6: number;
  8: number;
}

export interface TypographyTokens {
  bold: boolean;
  sm: string;
  base: string;
  lg: string;
  xl: string;
}

export interface BorderTokens {
  style: BorderStyle;
  color: string;
  focusColor: string;
}

export interface Theme {
  name: string;
  colors: ColorTokens;
  spacing: SpacingTokens;
  typography: TypographyTokens;
  border: BorderTokens;
}

export interface MotionContextValue {
  reduced: boolean;
}

export interface UnicodeContextValue {
  unicode: boolean;
}

const getEnv = (name: string): string | undefined =>
  typeof process !== "undefined" && process.env ? process.env[name] : undefined;

export const isReducedMotion = (): boolean =>
  getEnv("NO_MOTION") === "1" || getEnv("CI") === "true";

const detectUnicodeSupport = (): boolean => {
  if (typeof window !== "undefined") {
    return true;
  }

  if (getEnv("NO_UNICODE") === "1" || getEnv("NO_UNICODE") === "true") {
    return false;
  }

  const platform =
    typeof process !== "undefined" && process.platform
      ? process.platform
      : "browser";

  if (getEnv("WSL_DISTRO_NAME")) {
    return true;
  }
  if (getEnv("WT_SESSION")) {
    return true;
  }
  if (getEnv("TERM_PROGRAM") === "vscode") {
    return true;
  }
  if (getEnv("MSYSTEM")) {
    return false;
  }
  if (platform === "darwin" || platform === "linux") {
    return true;
  }

  return true;
};

export const isNoUnicode = (): boolean => !detectUnicodeSupport();

export const MotionContext = React.createContext<MotionContextValue>({
  reduced: isReducedMotion(),
});

export const UnicodeContext = React.createContext<UnicodeContextValue>({
  unicode: !isNoUnicode(),
});

export const useMotion = (): MotionContextValue =>
  React.useContext(MotionContext);

export const useUnicode = (): boolean =>
  React.useContext(UnicodeContext).unicode;

export const defaultTheme: Theme = {
  border: {
    color: "#4B5563",
    focusColor: "#8B5CF6",
    style: "round",
  },
  colors: {
    accent: "#8B5CF6",
    accentForeground: "#FFFFFF",
    background: "#000000",
    border: "#4B5563",
    error: "#EF4444",
    errorForeground: "#FFFFFF",
    focusRing: "#8B5CF6",
    foreground: "#FFFFFF",
    info: "#3B82F6",
    infoForeground: "#FFFFFF",
    muted: "#374151",
    mutedForeground: "#9CA3AF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#6B7280",
    secondaryForeground: "#FFFFFF",
    selection: "#7C3AED",
    selectionForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#000000",
  },
  name: "default",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};

interface ThemeContextValue {
  setTheme: (theme: Theme) => void;
  theme: Theme;
}

const ThemeContext = React.createContext<ThemeContextValue>({
  setTheme: () => {
    /* noop */
  },
  theme: defaultTheme,
});

export interface ThemeProviderProps {
  children: React.ReactNode;
  noUnicode?: boolean;
  reducedMotion?: boolean;
  theme?: Theme;
}

export const detectColorScheme = (): "dark" | "light" => {
  const colorFgBg = getEnv("COLORFGBG");
  if (colorFgBg) {
    const parts = colorFgBg.split(";");
    const background = Number.parseInt(parts.at(-1) ?? "0", 10);
    if (!Number.isNaN(background)) {
      return background <= 6 ? "dark" : "light";
    }
  }

  const termBackground = getEnv("TERM_BACKGROUND");
  if (termBackground === "light") {
    return "light";
  }
  if (termBackground === "dark") {
    return "dark";
  }

  return "dark";
};

export interface AutoThemeProviderProps {
  children: React.ReactNode;
  darkTheme: Theme;
  lightTheme: Theme;
}

export const AutoThemeProvider = ({
  children,
  darkTheme,
  lightTheme,
}: AutoThemeProviderProps) => {
  const scheme = detectColorScheme();
  return (
    <ThemeProvider theme={scheme === "dark" ? darkTheme : lightTheme}>
      {children}
    </ThemeProvider>
  );
};

export const ThemeProvider = ({
  children,
  noUnicode,
  reducedMotion,
  theme = defaultTheme,
}: ThemeProviderProps) => {
  const [currentTheme, setCurrentTheme] = React.useState(theme);

  React.useEffect(() => {
    setCurrentTheme(theme);
  }, [theme]);

  return (
    <MotionContext.Provider
      value={{ reduced: reducedMotion ?? isReducedMotion() }}
    >
      <UnicodeContext.Provider
        value={{
          unicode: noUnicode === undefined ? !isNoUnicode() : !noUnicode,
        }}
      >
        <ThemeContext.Provider
          value={{ setTheme: setCurrentTheme, theme: currentTheme }}
        >
          {children}
        </ThemeContext.Provider>
      </UnicodeContext.Provider>
    </MotionContext.Provider>
  );
};

export const useTheme = (): Theme => React.useContext(ThemeContext).theme;

export const useThemeUpdater = (): ((theme: Theme) => void) =>
  React.useContext(ThemeContext).setTheme;

export const createTheme = (
  overrides: Partial<Theme> & { name: string }
): Theme => ({
  ...defaultTheme,
  ...overrides,
  border: {
    ...defaultTheme.border,
    ...overrides.border,
  },
  colors: {
    ...defaultTheme.colors,
    ...overrides.colors,
  },
  spacing: {
    ...defaultTheme.spacing,
    ...overrides.spacing,
  },
  typography: {
    ...defaultTheme.typography,
    ...overrides.typography,
  },
});
