// This file is auto-generated by _add-components.mjs.
"use client";

import "ink-web/css";
import "@xterm/xterm/css/xterm.css";
import { InkTerminalBox } from "ink-web";
import * as React from "react";

import { ThemeProvider } from "@/components/ui/theme-provider";
import { terminalThemeMap, terminalThemeOptions } from "@/lib/terminal-themes";

export interface TerminalPreviewClientProps {
  children: React.ReactElement;
  defaultThemeKey?: keyof typeof terminalThemeMap;
  rows?: number;
}

const TerminalPreviewClient = ({
  children,
  defaultThemeKey = "default",
  rows = 18,
}: TerminalPreviewClientProps) => {
  const [themeKey, setThemeKey] =
    React.useState<keyof typeof terminalThemeMap>(defaultThemeKey);
  const activeTheme = terminalThemeMap[themeKey] ?? terminalThemeMap.default;

  const handleThemeChange = React.useCallback(
    (event: React.ChangeEvent<HTMLSelectElement>) => {
      setThemeKey(event.target.value as keyof typeof terminalThemeMap);
    },
    []
  );

  return (
    <div className="bg-surface border-border mt-6 overflow-hidden rounded-xl border">
      <div className="border-border flex items-center justify-between gap-4 border-b px-4 py-3">
        <div>
          <p className="text-sm font-medium">Live Terminal Preview</p>
          <p className="text-muted-foreground text-xs">
            Static docs page, client-side Ink terminal.
          </p>
        </div>
        <label className="flex items-center gap-2 text-sm">
          <span className="text-muted-foreground">Theme</span>
          <select
            className="bg-background border-input rounded-md border px-2 py-1 text-sm"
            value={themeKey}
            onChange={handleThemeChange}
          >
            {terminalThemeOptions.map((theme) => (
              <option key={theme.value} value={theme.value}>
                {theme.label}
              </option>
            ))}
          </select>
        </label>
      </div>
      <div className="bg-black">
        <InkTerminalBox
          className="min-h-[320px]"
          focus
          loading="skeleton"
          padding={12}
          rows={rows}
        >
          <ThemeProvider theme={activeTheme}>{children}</ThemeProvider>
        </InkTerminalBox>
      </div>
    </div>
  );
};

export default TerminalPreviewClient;
