// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.
import * as React from "react";

export type ExampleFramework = "ink" | "opentui";
type ExampleComponent = React.ComponentType<unknown>;
type ExampleModule = {
  default?: ExampleComponent;
} & Record<string, unknown>;

export interface ExampleEntry {
  component: React.LazyExoticComponent<ExampleComponent>;
  filePath: string;
  name: string;
}

const isExampleComponent = (value: unknown): value is ExampleComponent =>
  typeof value === "function";

const MissingExampleExport: ExampleComponent = () => null;

const resolveExampleComponent = (mod: ExampleModule): ExampleComponent => {
  if (isExampleComponent(mod.default)) {
    return mod.default;
  }

  const namedExport = Object.values(mod).find(isExampleComponent);

  return namedExport ?? MissingExampleExport;
};

export const ExamplesIndex: Record<
  ExampleFramework,
  Record<string, ExampleEntry>
> = {
  ink: {
    "alert-custom": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-custom");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/alert-custom.tsx",
      name: "alert-custom",
    },
    "alert-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/alert-demo.tsx",
      name: "alert-demo",
    },
    "alert-error": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-error");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/alert-error.tsx",
      name: "alert-error",
    },
    "alert-no-border": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-no-border");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/alert-no-border.tsx",
      name: "alert-no-border",
    },
    "alert-warning": {
      component: React.lazy(async () => {
        const mod = await import("./ink/alert-warning");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/alert-warning.tsx",
      name: "alert-warning",
    },
    "app-shell-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/app-shell-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/app-shell-demo.tsx",
      name: "app-shell-demo",
    },
    "aspect-ratio-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/aspect-ratio-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/aspect-ratio-demo.tsx",
      name: "aspect-ratio-demo",
    },
    "badge-basic": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-basic");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/badge-basic.tsx",
      name: "badge-basic",
    },
    "badge-bold": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-bold");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/badge-bold.tsx",
      name: "badge-bold",
    },
    "badge-custom-border": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-custom-border");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/badge-custom-border.tsx",
      name: "badge-custom-border",
    },
    "badge-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/badge-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/badge-demo.tsx",
      name: "badge-demo",
    },
    "banner-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/banner-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/banner-demo.tsx",
      name: "banner-demo",
    },
    "banner-error": {
      component: React.lazy(async () => {
        const mod = await import("./ink/banner-error");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/banner-error.tsx",
      name: "banner-error",
    },
    "banner-success": {
      component: React.lazy(async () => {
        const mod = await import("./ink/banner-success");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/banner-success.tsx",
      name: "banner-success",
    },
    "bar-chart-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/bar-chart-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/bar-chart-demo.tsx",
      name: "bar-chart-demo",
    },
    "big-text-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/big-text-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/big-text-demo.tsx",
      name: "big-text-demo",
    },
    "big-text-fonts": {
      component: React.lazy(async () => {
        const mod = await import("./ink/big-text-fonts");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/big-text-fonts.tsx",
      name: "big-text-fonts",
    },
    "box-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/box-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/box-demo.tsx",
      name: "box-demo",
    },
    "breadcrumb-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/breadcrumb-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/breadcrumb-demo.tsx",
      name: "breadcrumb-demo",
    },
    "bullet-list-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/bullet-list-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/bullet-list-demo.tsx",
      name: "bullet-list-demo",
    },
    "card-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/card-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/card-demo.tsx",
      name: "card-demo",
    },
    "center-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/center-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/center-demo.tsx",
      name: "center-demo",
    },
    "chat-message-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/chat-message-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/chat-message-demo.tsx",
      name: "chat-message-demo",
    },
    "chat-thread-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/chat-thread-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/chat-thread-demo.tsx",
      name: "chat-thread-demo",
    },
    "checkbox-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/checkbox-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/checkbox-demo.tsx",
      name: "checkbox-demo",
    },
    "checkbox-group-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/checkbox-group-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/checkbox-group-demo.tsx",
      name: "checkbox-group-demo",
    },
    "clipboard-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/clipboard-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/clipboard-demo.tsx",
      name: "clipboard-demo",
    },
    "clock-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/clock-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/clock-demo.tsx",
      name: "clock-demo",
    },
    "code-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/code-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/code-demo.tsx",
      name: "code-demo",
    },
    "code-multiline": {
      component: React.lazy(async () => {
        const mod = await import("./ink/code-multiline");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/code-multiline.tsx",
      name: "code-multiline",
    },
    "color-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/color-picker-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/color-picker-demo.tsx",
      name: "color-picker-demo",
    },
    "columns-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/columns-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/columns-demo.tsx",
      name: "columns-demo",
    },
    "command-palette-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/command-palette-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/command-palette-demo.tsx",
      name: "command-palette-demo",
    },
    "confirm-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/confirm-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/confirm-demo.tsx",
      name: "confirm-demo",
    },
    "data-grid-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/data-grid-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/data-grid-demo.tsx",
      name: "data-grid-demo",
    },
    "date-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/date-picker-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/date-picker-demo.tsx",
      name: "date-picker-demo",
    },
    "definition-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/definition-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/definition-demo.tsx",
      name: "definition-demo",
    },
    "dialog-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/dialog-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/dialog-demo.tsx",
      name: "dialog-demo",
    },
    "diff-view-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/diff-view-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/diff-view-demo.tsx",
      name: "diff-view-demo",
    },
    "digits-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/digits-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/digits-demo.tsx",
      name: "digits-demo",
    },
    "directory-tree-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/directory-tree-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/directory-tree-demo.tsx",
      name: "directory-tree-demo",
    },
    "divider-custom": {
      component: React.lazy(async () => {
        const mod = await import("./ink/divider-custom");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/divider-custom.tsx",
      name: "divider-custom",
    },
    "divider-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/divider-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/divider-demo.tsx",
      name: "divider-demo",
    },
    "drawer-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/drawer-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/drawer-demo.tsx",
      name: "drawer-demo",
    },
    "email-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/email-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/email-input-demo.tsx",
      name: "email-input-demo",
    },
    "embedded-terminal-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/embedded-terminal-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/embedded-terminal-demo.tsx",
      name: "embedded-terminal-demo",
    },
    "error-boundary-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/error-boundary-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/error-boundary-demo.tsx",
      name: "error-boundary-demo",
    },
    "file-change-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/file-change-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/file-change-demo.tsx",
      name: "file-change-demo",
    },
    "file-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/file-picker-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/file-picker-demo.tsx",
      name: "file-picker-demo",
    },
    "form-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/form-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/form-demo.tsx",
      name: "form-demo",
    },
    "form-field-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/form-field-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/form-field-demo.tsx",
      name: "form-field-demo",
    },
    "gauge-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/gauge-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/gauge-demo.tsx",
      name: "gauge-demo",
    },
    "git-status-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/git-status-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/git-status-demo.tsx",
      name: "git-status-demo",
    },
    "gradient-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/gradient-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/gradient-demo.tsx",
      name: "gradient-demo",
    },
    "gradient-presets": {
      component: React.lazy(async () => {
        const mod = await import("./ink/gradient-presets");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/gradient-presets.tsx",
      name: "gradient-presets",
    },
    "grid-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/grid-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/grid-demo.tsx",
      name: "grid-demo",
    },
    "heading-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/heading-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/heading-demo.tsx",
      name: "heading-demo",
    },
    "heat-map-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/heat-map-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/heat-map-demo.tsx",
      name: "heat-map-demo",
    },
    "help-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/help-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/help-demo.tsx",
      name: "help-demo",
    },
    "help-screen-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/help-screen-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/help-screen-demo.tsx",
      name: "help-screen-demo",
    },
    "image-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/image-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/image-demo.tsx",
      name: "image-demo",
    },
    "info-box-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/info-box-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/info-box-demo.tsx",
      name: "info-box-demo",
    },
    "json-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/json-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/json-demo.tsx",
      name: "json-demo",
    },
    "key-value-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/key-value-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/key-value-demo.tsx",
      name: "key-value-demo",
    },
    "keyboard-shortcuts-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/keyboard-shortcuts-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/keyboard-shortcuts-demo.tsx",
      name: "keyboard-shortcuts-demo",
    },
    "line-chart-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/line-chart-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/line-chart-demo.tsx",
      name: "line-chart-demo",
    },
    "link-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/link-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/link-demo.tsx",
      name: "link-demo",
    },
    "link-show-href": {
      component: React.lazy(async () => {
        const mod = await import("./ink/link-show-href");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/link-show-href.tsx",
      name: "link-show-href",
    },
    "list-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/list-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/list-demo.tsx",
      name: "list-demo",
    },
    "log-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/log-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/log-demo.tsx",
      name: "log-demo",
    },
    "login-flow-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/login-flow-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/login-flow-demo.tsx",
      name: "login-flow-demo",
    },
    "markdown-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/markdown-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/markdown-demo.tsx",
      name: "markdown-demo",
    },
    "masked-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/masked-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/masked-input-demo.tsx",
      name: "masked-input-demo",
    },
    "menu-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/menu-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/menu-demo.tsx",
      name: "menu-demo",
    },
    "modal-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/modal-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/modal-demo.tsx",
      name: "modal-demo",
    },
    "model-selector-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/model-selector-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/model-selector-demo.tsx",
      name: "model-selector-demo",
    },
    "multi-progress-compact": {
      component: React.lazy(async () => {
        const mod = await import("./ink/multi-progress-compact");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/multi-progress-compact.tsx",
      name: "multi-progress-compact",
    },
    "multi-progress-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/multi-progress-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/multi-progress-demo.tsx",
      name: "multi-progress-demo",
    },
    "multi-select-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/multi-select-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/multi-select-demo.tsx",
      name: "multi-select-demo",
    },
    "notification-center-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/notification-center-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/notification-center-demo.tsx",
      name: "notification-center-demo",
    },
    "number-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/number-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/number-input-demo.tsx",
      name: "number-input-demo",
    },
    "pagination-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/pagination-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/pagination-demo.tsx",
      name: "pagination-demo",
    },
    "panel-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/panel-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/panel-demo.tsx",
      name: "panel-demo",
    },
    "password-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/password-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/password-input-demo.tsx",
      name: "password-input-demo",
    },
    "path-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/path-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/path-input-demo.tsx",
      name: "path-input-demo",
    },
    "pie-chart-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/pie-chart-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/pie-chart-demo.tsx",
      name: "pie-chart-demo",
    },
    "popover-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/popover-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/popover-demo.tsx",
      name: "popover-demo",
    },
    "progress-bar-custom": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-bar-custom");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/progress-bar-custom.tsx",
      name: "progress-bar-custom",
    },
    "progress-bar-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-bar-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/progress-bar-demo.tsx",
      name: "progress-bar-demo",
    },
    "progress-circle-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-circle-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/progress-circle-demo.tsx",
      name: "progress-circle-demo",
    },
    "progress-circle-sizes": {
      component: React.lazy(async () => {
        const mod = await import("./ink/progress-circle-sizes");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/progress-circle-sizes.tsx",
      name: "progress-circle-sizes",
    },
    "qr-code-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/qr-code-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/qr-code-demo.tsx",
      name: "qr-code-demo",
    },
    "radio-group-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/radio-group-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/radio-group-demo.tsx",
      name: "radio-group-demo",
    },
    "scroll-view-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/scroll-view-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/scroll-view-demo.tsx",
      name: "scroll-view-demo",
    },
    "scroll-view-scrollbar": {
      component: React.lazy(async () => {
        const mod = await import("./ink/scroll-view-scrollbar");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/scroll-view-scrollbar.tsx",
      name: "scroll-view-scrollbar",
    },
    "search-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/search-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/search-input-demo.tsx",
      name: "search-input-demo",
    },
    "select-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/select-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/select-demo.tsx",
      name: "select-demo",
    },
    "setup-flow-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/setup-flow-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/setup-flow-demo.tsx",
      name: "setup-flow-demo",
    },
    "sidebar-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/sidebar-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/sidebar-demo.tsx",
      name: "sidebar-demo",
    },
    "skeleton-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/skeleton-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/skeleton-demo.tsx",
      name: "skeleton-demo",
    },
    "skeleton-static": {
      component: React.lazy(async () => {
        const mod = await import("./ink/skeleton-static");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/skeleton-static.tsx",
      name: "skeleton-static",
    },
    "spacer-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/spacer-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/spacer-demo.tsx",
      name: "spacer-demo",
    },
    "sparkline-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/sparkline-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/sparkline-demo.tsx",
      name: "sparkline-demo",
    },
    "spinner-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/spinner-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/spinner-demo.tsx",
      name: "spinner-demo",
    },
    "spinner-label": {
      component: React.lazy(async () => {
        const mod = await import("./ink/spinner-label");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/spinner-label.tsx",
      name: "spinner-label",
    },
    "spinner-styles": {
      component: React.lazy(async () => {
        const mod = await import("./ink/spinner-styles");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/spinner-styles.tsx",
      name: "spinner-styles",
    },
    "splash-screen-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/splash-screen-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/splash-screen-demo.tsx",
      name: "splash-screen-demo",
    },
    "stack-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/stack-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/stack-demo.tsx",
      name: "stack-demo",
    },
    "status-message-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/status-message-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/status-message-demo.tsx",
      name: "status-message-demo",
    },
    "status-message-variants": {
      component: React.lazy(async () => {
        const mod = await import("./ink/status-message-variants");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/status-message-variants.tsx",
      name: "status-message-variants",
    },
    "stopwatch-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/stopwatch-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/stopwatch-demo.tsx",
      name: "stopwatch-demo",
    },
    "streaming-text-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/streaming-text-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/streaming-text-demo.tsx",
      name: "streaming-text-demo",
    },
    "tabbed-content-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tabbed-content-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tabbed-content-demo.tsx",
      name: "tabbed-content-demo",
    },
    "table-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/table-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/table-demo.tsx",
      name: "table-demo",
    },
    "table-selectable": {
      component: React.lazy(async () => {
        const mod = await import("./ink/table-selectable");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/table-selectable.tsx",
      name: "table-selectable",
    },
    "table-sortable": {
      component: React.lazy(async () => {
        const mod = await import("./ink/table-sortable");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/table-sortable.tsx",
      name: "table-sortable",
    },
    "tabs-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tabs-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tabs-demo.tsx",
      name: "tabs-demo",
    },
    "tag-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tag-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tag-demo.tsx",
      name: "tag-demo",
    },
    "tag-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tag-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tag-input-demo.tsx",
      name: "tag-input-demo",
    },
    "text-area-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-area-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/text-area-demo.tsx",
      name: "text-area-demo",
    },
    "text-input-cursor": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-cursor");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/text-input-cursor.tsx",
      name: "text-input-cursor",
    },
    "text-input-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/text-input-demo.tsx",
      name: "text-input-demo",
    },
    "text-input-label": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-label");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/text-input-label.tsx",
      name: "text-input-label",
    },
    "text-input-placeholder": {
      component: React.lazy(async () => {
        const mod = await import("./ink/text-input-placeholder");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/text-input-placeholder.tsx",
      name: "text-input-placeholder",
    },
    "thinking-block-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/thinking-block-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/thinking-block-demo.tsx",
      name: "thinking-block-demo",
    },
    "time-picker-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/time-picker-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/time-picker-demo.tsx",
      name: "time-picker-demo",
    },
    "timer-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/timer-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/timer-demo.tsx",
      name: "timer-demo",
    },
    "toast-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/toast-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/toast-demo.tsx",
      name: "toast-demo",
    },
    "toast-error": {
      component: React.lazy(async () => {
        const mod = await import("./ink/toast-error");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/toast-error.tsx",
      name: "toast-error",
    },
    "toggle-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/toggle-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/toggle-demo.tsx",
      name: "toggle-demo",
    },
    "token-usage-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/token-usage-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/token-usage-demo.tsx",
      name: "token-usage-demo",
    },
    "tool-approval-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tool-approval-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tool-approval-demo.tsx",
      name: "tool-approval-demo",
    },
    "tool-call-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tool-call-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tool-call-demo.tsx",
      name: "tool-call-demo",
    },
    "tooltip-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tooltip-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tooltip-demo.tsx",
      name: "tooltip-demo",
    },
    "tree-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tree-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tree-demo.tsx",
      name: "tree-demo",
    },
    "tree-select-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/tree-select-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/tree-select-demo.tsx",
      name: "tree-select-demo",
    },
    "usage-monitor-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/usage-monitor-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/usage-monitor-demo.tsx",
      name: "usage-monitor-demo",
    },
    "virtual-list-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/virtual-list-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/virtual-list-demo.tsx",
      name: "virtual-list-demo",
    },
    "welcome-screen-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/welcome-screen-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/welcome-screen-demo.tsx",
      name: "welcome-screen-demo",
    },
    "wizard-demo": {
      component: React.lazy(async () => {
        const mod = await import("./ink/wizard-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/ink/wizard-demo.tsx",
      name: "wizard-demo",
    },
  },
  opentui: {
    "spinner-demo": {
      component: React.lazy(async () => {
        const mod = await import("./opentui/spinner-demo");

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: "examples/opentui/spinner-demo.tsx",
      name: "spinner-demo",
    },
  },
};
