// This file is auto-generated by _add-components.mjs.
import * as React from "react";

const clipboardWrite = (text: string) => {
  const encoded = Buffer.from(text).toString("base64");
  return `\u001B]52;c;${encoded}\u0007`;
};

export const useClipboard = () => {
  const write = React.useCallback(async (text: string) => {
    if (
      typeof navigator !== "undefined" &&
      navigator.clipboard &&
      typeof navigator.clipboard.writeText === "function"
    ) {
      await navigator.clipboard.writeText(text);
      return;
    }

    if (typeof process !== "undefined" && process.stdout?.write) {
      process.stdout.write(clipboardWrite(text));
    }
  }, []);

  return { write };
};
