import { promises as fs } from "node:fs";
import path from "node:path";

const root = process.cwd();
const examplesDir = path.join(root, "examples");
const outputFile = path.join(examplesDir, "__index__.ts");
const frameworks = ["ink", "opentui"];

const toPosixPath = (value: string) => value.split(path.sep).join("/");

const listExamples = async (framework: string) => {
  const frameworkDir = path.join(examplesDir, framework);

  try {
    const entries = await fs.readdir(frameworkDir, { withFileTypes: true });

    const names = entries
      .filter((entry) => entry.isFile() && entry.name.endsWith(".tsx"))
      .map((entry) => entry.name.replace(/\.tsx$/, ""));

    return [...names].toSorted((a, b) => a.localeCompare(b));
  } catch (error) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return [];
    }

    throw error;
  }
};

const buildExampleEntry = (framework: string, name: string) => {
  const importPath = `./${framework}/${name}`;
  const filePath = toPosixPath(path.join("examples", framework, `${name}.tsx`));

  return `    ${JSON.stringify(name)}: {
      component: React.lazy(async () => {
        const mod = await import(${JSON.stringify(importPath)});

        return { default: resolveExampleComponent(mod) };
      }),
      filePath: ${JSON.stringify(filePath)},
      name: ${JSON.stringify(name)},
    },`;
};

const buildFile = async () => {
  const records = await Promise.all(
    frameworks.map(
      async (framework) => [framework, await listExamples(framework)] as const
    )
  );

  const content = `// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.
import * as React from "react";

export type ExampleFramework = "ink" | "opentui";
type ExampleComponent = React.ComponentType<unknown>;
type ExampleModule = {
  default?: ExampleComponent;
} & Record<string, unknown>;

export interface ExampleEntry {
  component: React.LazyExoticComponent<ExampleComponent>;
  filePath: string;
  name: string;
}

const isExampleComponent = (value: unknown): value is ExampleComponent =>
  typeof value === "function";

const MissingExampleExport: ExampleComponent = () => null;

const resolveExampleComponent = (mod: ExampleModule): ExampleComponent => {
  if (isExampleComponent(mod.default)) {
    return mod.default;
  }

  const namedExport = Object.values(mod).find(isExampleComponent);

  return namedExport ?? MissingExampleExport;
};

export const ExamplesIndex: Record<ExampleFramework, Record<string, ExampleEntry>> = {
${records
  .map(
    ([framework, names]) => `  ${framework}: {
${names.map((name) => buildExampleEntry(framework, name)).join("\n")}
  },`
  )
  .join("\n")}
};
`;

  await fs.writeFile(outputFile, `${content.trim()}\n`);
};

await buildFile();
